import axios from 'axios'
import type { GetStaticProps, InferGetStaticPropsType, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { ViewTable } from '../domains/BKItem/features/ViewTable/ViewTable';
import { SelectRestaurant } from '../domains/Restaurant/features/SelectRestaurant'
import { useState } from 'react'
import { BKItem } from '../domains/BKItem'

export const getStaticProps: GetStaticProps = async (context) => {
  try {
    const cities: { name: string }[] = await axios.get(encodeURI(`/tabs/Города`), { baseURL: process.env.SHEETS_ID }).then(response => response.data)
    const data = await Promise.all(cities.map(async city => {
      return await axios.get(encodeURI(`/tabs/${city.name}`), { baseURL: process.env.SHEETS_ID }).then(response => ({
        name: city.name,
        data: response.data
      }))
    }))
    return {
      props: {
        data,
        cities
      }

    }
  } catch (e) {
    return {
      // notFound: true,
      props: {
        e: `${e} ${`${process.env.SHEETS_ID}/tabs/Города`}`
      }
    }
  }
}

type State = { type: 'city_selected', data: { name: string, data: BKItem[] } } | { type: 'error', text: string }


const Home: NextPage<{
  data: { name: string, data: BKItem[] }[],
  cities: { name: string }[],
  e?: Error
}> = ({ data, cities, e }) => {
  if (!data) return <>There was an error {e}</>
  const [state, setState] = useState<State>({ type: 'city_selected', data: data[0] })

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Найдите самые выгодные предложения в БК
        </h1>

        {(() => {
          switch (state.type) {
            case 'city_selected':
              return <>
                <p className={styles.description}>
                  Цены и короны указаны для <SelectRestaurant selectedRestaurant={state.data.name} cities={cities} onMsg={(msg) => {
                    switch (msg.type) {
                      case 'city_selected':
                        const selectedCityData = data.find(item => item.name === msg.city.name)
                        if (selectedCityData) {
                          setState({ type: 'city_selected', data: selectedCityData })
                        }
                        if (!selectedCityData) {
                          setState({ type: 'error', text: 'Выбран неверный город' })
                        }
                        break;

                      default:
                        break;
                    }
                  }} />
                </p>

                <ViewTable data={state.data.data} />
              </>
            case 'error':
              return <>
                <p className={styles.description}>
                  <SelectRestaurant selectedRestaurant={state.text} cities={cities} onMsg={(msg) => {
                    switch (msg.type) {
                      case 'city_selected':
                        const selectedCityData = data.find(item => item.name === msg.city.name)
                        if (selectedCityData) {
                          setState({ type: 'city_selected', data: selectedCityData })
                        }
                        if (!selectedCityData) {
                          setState({ type: 'error', text: 'Выбран неверный город' })
                        }
                        break;

                      default:
                        break;
                    }
                  }} />
                </p></>

            default:
              break;
          }
        })()}


      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
